# Generated by Django 3.2.2 on 2021-06-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('hole', models.IntegerField(default=0)),
                ('frequency_days', models.IntegerField(default=0)),
            ],
        ),
    ]
