# Generated by Django 3.2.2 on 2021-06-05 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_alter_task_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date',
            new_name='last_completed_date',
        ),
        migrations.AddField(
            model_name='task',
            name='next_due_date',
            field=models.DateField(default=datetime.date(2021, 6, 5)),
        ),
        migrations.AlterField(
            model_name='task',
            name='frequency_days',
            field=models.IntegerField(default=2),
        ),
    ]
