# Generated by Django 3.2.2 on 2021-06-11 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_alter_task_next_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=200)),
                ('hours_used', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('hole', models.IntegerField(default=0)),
                ('equipment', models.CharField(max_length=200)),
                ('hours', models.IntegerField(default=0)),
                ('date_completed', models.DateField(default='2001-01-01')),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='task',
            name='last_completed_date',
        ),
        migrations.AlterField(
            model_name='task',
            name='next_due_date',
            field=models.DateField(default=datetime.date(2021, 6, 11)),
        ),
    ]
