# Generated by Django 3.2.2 on 2021-08-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_auto_20210729_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hole',
            field=models.CharField(max_length=200),
        ),
    ]
