# Generated by Django 3.2.2 on 2021-08-21 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_alter_task_hole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='area',
        ),
        migrations.RemoveField(
            model_name='log',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='log',
            name='hole',
        ),
        migrations.RemoveField(
            model_name='log',
            name='hours',
        ),
    ]
