# Generated by Django 3.2.2 on 2021-08-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_auto_20210821_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='hole',
            field=models.CharField(default=29, max_length=200),
            preserve_default=False,
        ),
    ]
